"""BR_04_send_completion_email.py

Send HTML completion summary to admin (Logan Carpenter) via REUSABLE_send_notification.
    Subject: "Pipeline Complete — {YYYY-MM-DD} — {total_errors} errors"
    Body: HTML table of all 15 metrics + error highlights + link to Errors tab.
    EscalateOnFailure: False (failure here does not crash pipeline).

Exceptions:
    SE-01: All channels fail → write to stdout + logs/completion_{date}.json.
"""

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict
from zoneinfo import ZoneInfo

from src.reusable.send_notification import send_notification

logger = logging.getLogger(__name__)

_ET_TZ = ZoneInfo("America/New_York")
_LOGS_DIR = Path(__file__).parent.parent.parent / "logs"

_METRIC_LABELS = {
    "pipeline_run_date": "Run Date",
    "pipeline_start_time": "Start Time",
    "pipeline_end_time": "End Time",
    "feeds_attempted": "Feeds Attempted",
    "feeds_errored": "Feeds Errored",
    "articles_fetched": "Articles Fetched",
    "articles_new": "Articles New (deduplicated)",
    "articles_classified": "Articles Classified",
    "articles_classification_errors": "Classification Errors",
    "digests_generated": "Digests Generated",
    "emails_sent": "Emails Sent",
    "emails_failed": "Emails Failed",
    "slack_messages_sent": "Slack Messages Sent",
    "total_errors": "Total Errors",
    "error_highlights": "Error Highlights",
}


def _build_html(summary: Dict[str, Any], spreadsheet_url: str) -> str:
    run_date = summary.get("pipeline_run_date", "")
    total_errors = summary.get("total_errors", 0)
    status_color = "#c0392b" if total_errors > 0 else "#27ae60"
    status_label = f"{total_errors} error(s)" if total_errors > 0 else "Clean run"

    rows_html = ""
    for key, label in _METRIC_LABELS.items():
        value = summary.get(key, "")
        if key == "error_highlights":
            highlights = value if isinstance(value, list) else []
            if highlights:
                cell = "<ol>" + "".join(f"<li>{h}</li>" for h in highlights) + "</ol>"
            else:
                cell = "<em>None</em>"
        else:
            cell = str(value)
        bg = "#fff8f8" if key in ("total_errors", "feeds_errored", "emails_failed",
                                   "articles_classification_errors") and str(value) not in ("0", "") else "white"
        rows_html += (
            f'<tr style="background:{bg};">'
            f'<td style="padding:6px 12px;font-weight:bold;border-bottom:1px solid #eee;">{label}</td>'
            f'<td style="padding:6px 12px;border-bottom:1px solid #eee;">{cell}</td>'
            f'</tr>\n'
        )

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;color:#222;max-width:700px;margin:0 auto;">
  <h2 style="border-bottom:2px solid #2c3e50;padding-bottom:8px;">
    Zero Industrial Pipeline — {run_date}
  </h2>
  <p style="font-size:1.1em;">
    Status: <strong style="color:{status_color};">{status_label}</strong>
  </p>
  <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
    <thead>
      <tr style="background:#2c3e50;color:white;">
        <th style="padding:8px 12px;text-align:left;">Metric</th>
        <th style="padding:8px 12px;text-align:left;">Value</th>
      </tr>
    </thead>
    <tbody>
      {rows_html}
    </tbody>
  </table>
  <p>
    <a href="{spreadsheet_url}" style="color:#2980b9;">
      View Errors tab in Google Sheets &rarr;
    </a>
  </p>
  <p style="color:#999;font-size:0.85em;">
    Generated by Zero Industrial Intelligence Digest pipeline.
  </p>
</body>
</html>"""


def _write_local_fallback(summary: Dict[str, Any]) -> None:
    """Write summary to stdout and logs/completion_{date}.json."""
    run_date = summary.get("pipeline_run_date", "unknown").replace("-", "")
    print("\n=== PIPELINE COMPLETION SUMMARY (email delivery failed) ===")
    for key, label in _METRIC_LABELS.items():
        print(f"  {label}: {summary.get(key, '')}")
    print("=" * 60)

    _LOGS_DIR.mkdir(parents=True, exist_ok=True)
    path = _LOGS_DIR / f"completion_{run_date}.json"
    try:
        with open(path, "w") as fh:
            json.dump(summary, fh, indent=2, default=str)
        logger.info("Completion summary written to %s", path)
    except Exception as exc:
        logger.error("Could not write completion JSON fallback: %s", exc)


def send_completion_email(summary: Dict[str, Any], admin_email: str) -> Dict:
    """Send HTML pipeline completion summary to admin.

    Never raises — if all channels fail, writes to stdout and local JSON.
    Returns the send_notification result dict.
    """
    run_date = summary.get("pipeline_run_date", datetime.now(_ET_TZ).strftime("%Y-%m-%d"))
    total_errors = summary.get("total_errors", 0)
    subject = f"Pipeline Complete \u2014 {run_date} \u2014 {total_errors} errors"

    spreadsheet_id = os.environ.get("SPREADSHEET_ID", "")
    spreadsheet_url = (
        f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}"
        if spreadsheet_id else "#"
    )

    body_html = _build_html(summary, spreadsheet_url)

    try:
        result = send_notification(
            to=admin_email,
            subject=subject,
            body=body_html,
            body_is_html=True,
            escalate_on_failure=False,
        )
        if result.get("success"):
            logger.info(
                "Completion email sent to %s via %s.", admin_email, result.get("channel_used")
            )
        else:
            logger.warning(
                "SE-01: Completion email delivery failed: %s — writing local fallback.",
                result.get("error_if_any"),
            )
            _write_local_fallback(summary)
        return result
    except Exception as exc:
        logger.error("SE-01: send_notification raised unexpectedly: %s", exc)
        _write_local_fallback(summary)
        return {"channel_used": "local_fallback", "success": False, "error_if_any": str(exc)}
